/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Machine;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sms.testXML;

/**
 *
 * @author Jacob Mahto
 */
public class attRep extends javax.swing.JFrame {
    static int srCol=2,nameCol=3,stdCol=4,statusCol=6;
public static void loadDates(){
try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                
                String query="SELECT distinct date FROM studentlog;";
                ResultSet rs=stmt.executeQuery(query);
                
                               
                while(rs.next()){
                jComboBox1.addItem(rs.getString(1));
                }
                rs.close();
                con.close();
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error loading dates !!");
} 
}
    /**
     * Creates new form attRep
     */
    public attRep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        abTA = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        countTF = new javax.swing.JLabel();
        overCB = new javax.swing.JCheckBox();
        hhTF = new javax.swing.JTextField();
        mmTF = new javax.swing.JTextField();
        hhmmTF = new javax.swing.JTextField();
        urlTF = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        overCB1 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        sesTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        dHTF = new javax.swing.JTextField();
        dMTF = new javax.swing.JTextField();
        dATF = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TECH-RES MACHINE");

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TECH-RES MACHINE CONNECT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("LOAD TODAY'S REPORT FROM CLOUD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setText("LOAD FROM MACHINE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "SR", "Name", "STD", "Check Time", "Status", "By", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORT GENERATION");

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setText("Add Manual Entry");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton5.setText("Delete day's Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton6.setText("Delete rows temp.");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Machine Report");

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Repetitions");

        abTA.setColumns(20);
        abTA.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        abTA.setLineWrap(true);
        abTA.setRows(5);
        jScrollPane4.setViewportView(abTA);

        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton10.setText("Copy");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "SR", "Name", "STD", "Check Time", "Status", "By", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTable2);

        jButton14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton14.setText("Message Dep/Ar.");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addGap(2, 2, 2)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(113, 113, 113))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton14)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(512, 512, 512))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379)
                .addComponent(jButton10)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton14)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("It may take upto 5 minutes to reflect the recent machine changes.");

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PG", "NUR", "LKG", "UKG", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI Arts-A", "XI Arts-B", "XI Arts-C", "XI Commerce-A", "XI Commerce-B", "XI Commerce-C", "XII Arts-A", "XII Arts-B", "XII Arts-C", "XII Commerce-A", "XII Commerce-B", "XII Commerce-C" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        countTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        countTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        overCB.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        overCB.setText("Overall");
        overCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overCBActionPerformed(evt);
            }
        });

        hhTF.setText("07");

        mmTF.setText("30");

        hhmmTF.setText("0730");

        urlTF.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        urlTF.setText("https://docs.google.com/spreadsheets/d/e/2PACX-1vTZUqmnw3bA8WSmVg3bsIy5wb-YDO7Y7OkuP84b0tt7cGvV7HJQNF_nbm_9qlltnE_0y-K_fxFD5TnU/pub?output=csv");
        urlTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTFActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton8.setText("No Repetition");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Total Entries : ");

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton7.setText("Messege Pr.");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        overCB1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        overCB1.setText("SMS REPEAT");

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton9.setText("Absentees");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        sesTF.setText("2018");
        sesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("Session : ");

        jButton11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton11.setText("Messege Ab.");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton12.setText("Refresh");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        dHTF.setText("07");

        dMTF.setText("30");

        dATF.setText("0730");

        jButton13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton13.setText("Dep./Arr.");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hhTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hhmmTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dHTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dMTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dATF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(overCB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(overCB1)
                                        .addGap(7, 7, 7)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(countTF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(urlTF))
                    .addComponent(countTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hhTF)
                                .addComponent(mmTF)
                                .addComponent(hhmmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dHTF)
                                .addComponent(dMTF)
                                .addComponent(dATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(overCB)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2)
                                .addComponent(overCB1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton11)
                                        .addComponent(jButton13))
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton7.setEnabled(true);
        DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
        DefaultTableModel table2=(DefaultTableModel)jTable2.getModel();
DownloadPage machine=new DownloadPage();
machine.hh=Double.parseDouble(hhTF.getText());
machine.mm=Double.parseDouble(mmTF.getText());
machine.hhmm=hhmmTF.getText();

try{
 URL url = new URL(urlTF.getText());
 machine.internetRead(url);
}
catch(Exception e){
JOptionPane.showMessageDialog(null, "Error Connecting to Internet Cloud!");
}

try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                overCB.setSelected(false);
                 ResultSet rs=null;
                 int j=0;
                 while(j<table.getRowCount()){
                table.removeRow(j);
                }
                 j=0;
                 while(j<table2.getRowCount()){
                table2.removeRow(j);
                }
                 
                 int ind=1;
                for(int i=0;i<=machine.entries;i++){//entries is the last index and not length
                String query="SELECT name,class,fcon,mcon FROM studentinfo WHERE sr='"+machine.timeDate[i][6]+"';";
                System.out.println("%%%%"+machine.timeDate[i][6]);
                String contact="9636509907";
                rs=stmt.executeQuery(query);
                if(rs.next()==false){
                jTextArea1.append("Error in :"+(i+2)+"\t"+"Sr. Entry : "+machine.timeDate[i][6]+"\n");
                }
                else{
                rs.beforeFirst();
                }
                 while(rs.next()){
                     System.out.println(ind+"((((");
                     if((rs.getString("fcon").trim()).equals("")){
                         if((rs.getString("mcon").trim()).equals("")){
                         contact="9636509907";
                         }
                         else {                         contact=rs.getString("mcon");}
                     }
                     else {
                     contact=rs.getString("fcon");
                     
                     
                     }
                     try{
                     double ch=Double.parseDouble(contact.trim());
                     }
                     catch(Exception e){
                     contact="9636509907";
                     }
                     contact=contact.trim();
                table.addRow(new Object[]{
               ind, machine.timeDate[i][0],machine.timeDate[i][6],rs.getString(1),rs.getString(2),machine.timeDate[i][1],machine.timeDate[i][5],machine.timeDate[i][3]+" h-"+machine.timeDate[i][4]+" m",contact});  
                table2.addRow(new Object[]{
               ind, machine.timeDate[i][0],machine.timeDate[i][6],rs.getString(1),rs.getString(2),machine.timeDate[i][1],machine.timeDate[i][5],machine.timeDate[i][3]+" h-"+machine.timeDate[i][4]+" m",contact}); 
                ind++;
                jLabel4.setText(machine.timeDate[i][0]); 
                if((ind-2)!=i){
                
                }
                } 
                 rs.close();
                }
                
                countTF.setText(machine.entries+1+"");
                jButton9.setEnabled(true);
                
                
               
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error fetching info.");
} 


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
table.addRow(new Object[]{});

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
String vals[][]=new String[table.getRowCount()][table.getColumnCount()-1];
String query="";        
        try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                
                for(int i=0;i<table.getRowCount();i++){
                for(int j=0;j<table.getColumnCount()-1;j++){
                vals[i][j]=(String)table.getValueAt(i, j+1);System.out.println("HI");
                }   
                }
                String queryDel="DELETE FROM STUDENTLOG WHERE date='"+jLabel4.getText()+"';";
                
                stmt.execute(queryDel);
                for(int i=0;i<table.getRowCount();i++){
                query="INSERT INTO STUDENTLOG VALUES('"+vals[i][0]+"','"+vals[i][1]+"','"+vals[i][2]+"','"+vals[i][3]+"','"+vals[i][4]+"','"+vals[i][5]+"','"+vals[i][6]+"','"+vals[i][7]+"');";
                stmt.execute(query);
                }         
                
                con.close();
                JOptionPane.showMessageDialog(null, "Saved !");
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error saving !!");
} 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
overCB.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                String delQuery="DELETE FROM STUDENTLOG WHERE date='"+jLabel4.getText()+"';";
                stmt.execute(delQuery);
                JOptionPane.showMessageDialog(null, "Deleted.");
                jButton12.doClick();
                
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error fetching info.");
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
DefaultTableModel table2=(DefaultTableModel)jTable2.getModel();
try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                overCB.setSelected(false);
                String query="SELECT * FROM studentlog WHERE std='"+(String)jComboBox2.getSelectedItem()+"' AND DATE='"+(String)jComboBox1.getSelectedItem()+"';";
                ResultSet rs=stmt.executeQuery(query);
                
                rs.last();
                int countR=rs.getRow();
                countTF.setText(rs.getRow()+"");
                rs.beforeFirst();
                int j=0;
                while(j<table.getRowCount()){
                table.removeRow(j);
                }
                j=0;
                while(j<table2.getRowCount()){
                table2.removeRow(j);
                }
                
                int i=1;
                while(rs.next()){
                table.addRow(new Object[]{
                i,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});  
                table2.addRow(new Object[]{
                i,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});  
                jLabel4.setText(rs.getString(1));
                i++;
               
                } 
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error fetching info.");
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
 int[] selectedRows = jTable1.getSelectedRows();
 //System.out.println(selectedRows[0]+"---"+selectedRows[1]+"$$$$"+selectedRows.length);
 
for(int i=selectedRows.length-1;i>=0;i--){
tab.removeRow(selectedRows[i]);
}
JOptionPane.showMessageDialog(null, "Selected entries deleted from the database !","Success !",1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void urlTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTFActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(overCB1.isSelected()==false){
jButton8.doClick();
}
else{}
        
        testXML mes=new testXML();
DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
for(int i=0;i<tab.getRowCount();i++){
     testXML.present((String)tab.getValueAt(i,3), (String)tab.getValueAt(i,6),(String)tab.getValueAt(i,5),(String) tab.getValueAt(i,1),(String) tab.getValueAt(i,8),(String)tab.getValueAt(i, 7));
String response=testXML.strResponseBody;
   int find=response.indexOf("<error>");
   if(find==-1){
   tab.setValueAt("SENT", i, 0);
   }
   else{
   tab.setValueAt("FAILED", i, 0);
   }
}
JOptionPane.showMessageDialog(null, "Success!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
int limit=tab.getRowCount();

for(int i=0;i<limit;i++){
    int repeat=0;
String check=(String)tab.getValueAt(i, 2);
for(int j=i+1;j<limit;j++){
    String check1=(String)tab.getValueAt(j, 2);
if(check1.equals(check)==true){
repeat++;
tab.removeRow(j);
j--;
limit--;
}
}
if(repeat>0){
jTextArea2.append((String)tab.getValueAt(i, 2)+" : "+(String)tab.getValueAt(i, 3)+" : "+(String)tab.getValueAt(i, 4)+" --"+repeat+"\n");
}
}
for(int k=0;k<tab.getRowCount();k++){
tab.setValueAt(k+1, k, 0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
jButton7.setEnabled(false);
        DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
String contact="9636509907";
int counting=0;
        jButton8.doClick();
        jButton9.setEnabled(false);
        String srList[]=new String[1000];
String srData[][]=new String[1000][3];
DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
DefaultTableModel copyTab;

int stdNo=jComboBox2.getItemCount();
abTA.setText("----------------MK PUBLIC SR. SEC. SCHOOL------------\n---------------TECH-RES MACHINE CONNECT---------------\n");
int cnt=0;
for(int i=0;i<stdNo;i++){
String std=(String)jComboBox2.getItemAt(i);
abTA.append("\n\n-----------ABSENTESS OF CLASS : "+std+" ------------TOTAL STUDENTS : ");
int studCount=0;
try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                
                String query="SELECT sr,name,fcon,mcon from studentinfo where session='"+sesTF.getText()+"' AND class='"+std+"';";
                ResultSet rs=stmt.executeQuery(query);
                
                
                while(rs.next()){
                srData[studCount][0]=rs.getString(1);//sr
                srData[studCount][1]=rs.getString(2);//name
                
                try{
                
                        if((rs.getString("fcon").trim()).equals("")){
                         if((rs.getString("mcon").trim()).equals("")){
                         contact="9636509907";
                         }
                         else {                         contact=rs.getString("mcon");}
                     }
                     else {
                     contact=rs.getString("fcon");
                     
                     
                     }
                        
                     try{
                     double ch=Double.parseDouble(contact.trim());
                     }
                     catch(Exception e){
                     contact="9636509907";
                     }
                     contact=contact.trim();
                     srData[studCount][2]=contact;
                
                }
                catch(Exception e){}
                
                studCount++; 
                
                }            
                abTA.append(studCount+"-----------NO. OF ABSENTEES : ");
                rs.close();
                con.close();
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error fetching info.");
} 
try{
    int abCount=0;
    String info="";
for(int j=0;j<studCount;j++){
int mark=-1;
    for(int k=0;k<tab.getRowCount();k++){
    if(srData[j][0].equals(tab.getValueAt(k, srCol))){
    mark=k;
       }
    else{
        
    
    }
    }
    if(mark==-1){
        abCount++;
   info+=("SR : "+srData[j][0]+" - NAME : "+srData[j][1]+" , ");
   table.addRow(new Object[]{++counting,jLabel4.getText(),srData[j][0],srData[j][1],jComboBox2.getItemAt(i),"","Absent","",srData[j][2]});  
    }      
}
abTA.append(abCount+" --\n");
abTA.append(info);
}
catch(Exception e){}


}
int rows=table.getRowCount();
for(int jacob=rows-1;jacob>=0;jacob--){
if(table.getValueAt(jacob, statusCol).equals("Absent")){}
else {
table.removeRow(jacob);
}
}




        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sesTFActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
abTA.selectAll();
        abTA.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
if(overCB1.isSelected()==false){
jButton8.doClick();
}
else{}
        
        testXML mes=new testXML();
DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
for(int i=0;i<tab.getRowCount();i++){
    testXML.absent((String)tab.getValueAt(i,3), (String)tab.getValueAt(i,6),(String) tab.getValueAt(i,1),(String) tab.getValueAt(i,8));
   String response=testXML.strResponseBody;
   int find=response.indexOf("<error>");
   if(find==-1){
   tab.setValueAt("SENT", i, 0);
   }
   else{
   tab.setValueAt("FAILED", i, 0);
   }
   
}
JOptionPane.showMessageDialog(null, "Success!");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
dispose();
new attRep().setVisible(true);
loadDates();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void overCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overCBActionPerformed
DefaultTableModel table=(DefaultTableModel)jTable1.getModel();
try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost","root","lion");
                Statement stmt=con.createStatement();
                String query1="USE rsl;";                
                stmt.execute(query1);              
                  
                String query="SELECT * FROM studentlog WHERE DATE='"+(String)jComboBox1.getSelectedItem()+"';";
                ResultSet rs=stmt.executeQuery(query);
                
                rs.last();
                int countR=rs.getRow();
                countTF.setText(rs.getRow()+"");
                rs.beforeFirst();
                int j=0;
                while(j<table.getRowCount()){
                table.removeRow(j);
                }
                int i=1;
                while(rs.next()){
                table.addRow(new Object[]{
                i++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});  
                jLabel4.setText(rs.getString(1));
                } 
                
}
catch(Exception E){
System.out.println(E);
JOptionPane.showMessageDialog(null,E+"\n Error fetching info.");
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_overCBActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
DefaultTableModel tab=(DefaultTableModel)jTable1.getModel();
int limit=tab.getRowCount();

//actual coding-----coding for arrival
for(int i=0;i<limit;i++){
    int repeat=0;
String check=(String)tab.getValueAt(i, 2);
for(int j=i+1;j<limit;j++){
    String check1=(String)tab.getValueAt(j, 2);
if(check1.equals(check)==true){
repeat++;
tab.removeRow(j);
j--;
limit--;
}

}
if(repeat>0){
jTextArea2.append((String)tab.getValueAt(i, 2)+" : "+(String)tab.getValueAt(i, 3)+" : "+(String)tab.getValueAt(i, 4)+" --"+repeat+"\n");
}
}
for(int k=0;k<tab.getRowCount();k++){
tab.setValueAt(k+1, k, 0);
} 


//coding for departure table
DefaultTableModel tab2=(DefaultTableModel)jTable2.getModel();

for(int ci=tab2.getRowCount()-1;ci>=0;ci--){
    String check1=(String)tab2.getValueAt(ci, 2);
    for(int j=ci-1;j>=0;j--){
    String check2=(String)tab2.getValueAt(j, 2);
    if(check1.equals(check2)){
    tab2.removeRow(j);
    ci--;
    }
    }

}



// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
DefaultTableModel tab1=(DefaultTableModel)jTable1.getModel();
DefaultTableModel tab2=(DefaultTableModel)jTable2.getModel();
testXML mes=new testXML();
String ar,dep,name,contact="9636509907",day,status,statusby;
        for(int i=0;i<tab1.getRowCount();i++){
        ar=(String)tab1.getValueAt(i, 5);
        contact=(String)tab1.getValueAt(i, 8);
        dep=ar;//default , in case dep is not available
        day=(String)tab1.getValueAt(i, 1);
        name=(String)tab1.getValueAt(i, 3);
        status=(String)tab1.getValueAt(i, 6);
        statusby=(String)tab1.getValueAt(i, 7);
        
        for(int j=0;j<tab2.getRowCount();j++){
        if(((String)tab2.getValueAt(j, 3)).equals(name)){
        dep=(String)tab2.getValueAt(j, 5);
        };            
        }
         mes.fullDetail(name,status, ar, dep,day, contact,statusby);
          String response=testXML.strResponseBody;
   int find=response.indexOf("<error>");
   if(find==-1){
   tab1.setValueAt("SENT", i, 0);
   
   }
   else{
   tab1.setValueAt("FAILED", i, 0);
   }
        }
        JOptionPane.showMessageDialog(null, "COMPLETED !");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attRep().setVisible(true);
                loadDates();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea abTA;
    private javax.swing.JLabel countTF;
    private javax.swing.JTextField dATF;
    private javax.swing.JTextField dHTF;
    private javax.swing.JTextField dMTF;
    private javax.swing.JTextField hhTF;
    private javax.swing.JTextField hhmmTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField mmTF;
    private javax.swing.JCheckBox overCB;
    private javax.swing.JCheckBox overCB1;
    private javax.swing.JTextField sesTF;
    private javax.swing.JTextField urlTF;
    // End of variables declaration//GEN-END:variables
}
